/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function greet(a: number, b: number): void;
export function __wbg_glcanvas_free(a: number): void;
export function __wbg_get_glcanvas_window(a: number): number;
export function __wbg_set_glcanvas_window(a: number, b: number): void;
export function __wbg_get_glcanvas_level(a: number): number;
export function __wbg_set_glcanvas_level(a: number, b: number): void;
export function __wbg_get_glcanvas_scale_transverse(a: number): number;
export function __wbg_set_glcanvas_scale_transverse(a: number, b: number): void;
export function __wbg_get_glcanvas_scale_sagittal(a: number): number;
export function __wbg_set_glcanvas_scale_sagittal(a: number, b: number): void;
export function __wbg_get_glcanvas_scale_coronal(a: number): number;
export function __wbg_set_glcanvas_scale_coronal(a: number, b: number): void;
export function __wbg_get_glcanvas_pan_transverse_x(a: number): number;
export function __wbg_set_glcanvas_pan_transverse_x(a: number, b: number): void;
export function __wbg_get_glcanvas_pan_transverse_y(a: number): number;
export function __wbg_set_glcanvas_pan_transverse_y(a: number, b: number): void;
export function __wbg_get_glcanvas_pan_sagittal_x(a: number): number;
export function __wbg_set_glcanvas_pan_sagittal_x(a: number, b: number): void;
export function __wbg_get_glcanvas_pan_sagittal_y(a: number): number;
export function __wbg_set_glcanvas_pan_sagittal_y(a: number, b: number): void;
export function __wbg_get_glcanvas_pan_coronal_x(a: number): number;
export function __wbg_set_glcanvas_pan_coronal_x(a: number, b: number): void;
export function __wbg_get_glcanvas_pan_coronal_y(a: number): number;
export function __wbg_set_glcanvas_pan_coronal_y(a: number, b: number): void;
export function __wbg_get_glcanvas_slice_transverse(a: number): number;
export function __wbg_set_glcanvas_slice_transverse(a: number, b: number): void;
export function __wbg_get_glcanvas_slice_sagittal(a: number): number;
export function __wbg_set_glcanvas_slice_sagittal(a: number, b: number): void;
export function __wbg_get_glcanvas_slice_coronal(a: number): number;
export function __wbg_set_glcanvas_slice_coronal(a: number, b: number): void;
export function glcanvas_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function glcanvas_set_window(a: number, b: number): void;
export function glcanvas_set_level(a: number, b: number): void;
export function glcanvas_set_scale_transverse(a: number, b: number): void;
export function glcanvas_set_scale_sagittal(a: number, b: number): void;
export function glcanvas_set_scale_coronal(a: number, b: number): void;
export function glcanvas_set_pan_transverse_x(a: number, b: number): void;
export function glcanvas_set_pan_transverse_y(a: number, b: number): void;
export function glcanvas_set_pan_sagittal_x(a: number, b: number): void;
export function glcanvas_set_pan_sagittal_y(a: number, b: number): void;
export function glcanvas_set_pan_coronal_x(a: number, b: number): void;
export function glcanvas_set_pan_coronal_y(a: number, b: number): void;
export function glcanvas_set_pan_dx(a: number, b: number): void;
export function glcanvas_set_pan_dy(a: number, b: number): void;
export function glcanvas_set_slice_transverse(a: number, b: number): void;
export function glcanvas_set_slice_sagittal(a: number, b: number): void;
export function glcanvas_set_slice_coronal(a: number, b: number): void;
export function glcanvas_load_shaders(a: number): void;
export function glcanvas_load_volume_from_file(a: number, b: number, c: number, d: number, e: number): void;
export function glcanvas_setup_geometry(a: number): void;
export function glcanvas_render(a: number): void;
export function start(a: number, b: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hb5f4ab0214dc77a0(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
